### ISSUE TITLE
Simplified control file

### ISSUE THREAD

**Issue by redcurry** [macroevolution/bamm#124]
Several options will now be "not required" and therefore hidden by default from the user. These are the scaling parameters and move frequencies. Initial parameter values should be optional, with defaults calculated automatically (see Issue #122). Prior values should be calculated as BAMMtools does. For MC3 options, just keep the number of chains. Also, segLength and minCladeSizeForShift should be hidden.

**Comment by rmarquezp** [comment]
Hello! I tried changing the minCladeSizeForShift parameter in my control file and got the following error: 

```
ERROR: One or more parameters from the control file does not
correspond to valid model parameters. Make sure that you are
running the correct version of BAMM or check that the following
parameters are spelled correctly:

      minCladeSizeForShift
```

Has the way to specify this parameter changed (or, can it still be set)? 

Thanks!

**Comment by ptitle** [comment]
Hi,
I just just tested this out, and I had no trouble changing the value for `minCladeSizeForShift` in the control file. If you post this question on the BAMM google group, and include your control file, I'd be happy to take a look.

https://groups.google.com/g/bamm-project

**Comment by rmarquezp** [comment]
Thanks! I think I've found the problem. I'm running a phenotypic rate
analysis and this parameter seems to be exclusive to the
speciation/extinction model. If this is the case then feel free to close,
otherwise I'll post on Google groups.

**Comment by ptitle** [comment]
Yes, that is correct. If you were to grab the trait template control file, that argument is not present.
