### ISSUE TITLE
plot 

### ISSUE THREAD

**Issue by majssssa** [macroevolution/bamm#141]
How do I plot extinction and  c net diversification (green) from the BAMM analysis.

**Comment by ptitle** [comment]
Hi,
Have you seen the bamm-project website? It has lots of tutorials, explanations and walk-throughs for processing and analyzing BAMM output.
For instance: http://bamm-project.org/postprocess.html

**Comment by majssssa** [comment]
Hi,
Thanks for your reply, the problem was solved after I read the page,
